env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
plugins: ["eslint-plugin-react"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  # sourceType: "module"
  ecmaFeatures:
    jsx: true
rules: {
  
}
parser: babel-eslint
